/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package imu;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lcm_original implements lcm.lcm.LCMEncodable
{
    public float accx_o;
    public float accy_o;
    public float accz_o;
 
    public lcm_original()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe23a1d927e1854d3L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(imu.lcm_original.class))
            return 0L;
 
        classes.add(imu.lcm_original.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.accx_o); 
 
        outs.writeFloat(this.accy_o); 
 
        outs.writeFloat(this.accz_o); 
 
    }
 
    public lcm_original(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lcm_original(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static imu.lcm_original _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        imu.lcm_original o = new imu.lcm_original();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.accx_o = ins.readFloat();
 
        this.accy_o = ins.readFloat();
 
        this.accz_o = ins.readFloat();
 
    }
 
    public imu.lcm_original copy()
    {
        imu.lcm_original outobj = new imu.lcm_original();
        outobj.accx_o = this.accx_o;
 
        outobj.accy_o = this.accy_o;
 
        outobj.accz_o = this.accz_o;
 
        return outobj;
    }
 
}

